services:
  jaeger:
    #container_name: op-jaeger-1
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "6831:6831/udp"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: 1

  prometheus:
    #container_name: op-prometheus-1
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml


  otel-collector:
    #container_name: op-otel-collector-1
    image: otel/opentelemetry-collector:latest
    ports:
      - "4320:4320" # OTLP gRPC
      - "4321:4321" # OTLP HTTP
      - "9464:9464"
    volumes:
      - ./collector-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      - jaeger
      - prometheus


  api_1:
    #container_name: op-api_1-1
    build:
        context: .
        dockerfile: DockerfileApi1
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector

