services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "6831:6831/udp"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: 1

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  latency-app:
    build:
        context: .
        dockerfile: DockerfileLatency
    ports:
      - "8001:8001"
    depends_on:
      - jaeger
      - prometheus
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://host.docker.internal:4318/v1/traces
      METRICS_EXPORTER_PORT: 8002

  sort-app:
    build: 
        context: .
        dockerfile: DockerfileSort
    ports:
      - "8000:8000"
    depends_on:
      - jaeger
      - prometheus
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://host.docker.internal:4318/v1/traces
      METRICS_EXPORTER_PORT: 8003

