services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "6831:6831/udp"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: 1

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4320:4320" # OTLP gRPC
      - "4321:4321" # OTLP HTTP
    volumes:
      - ./collector-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      - jaeger

  latency-app:
    build:
        context: .
        dockerfile: DockerfileLatency
    ports:
      - "8001:8001"
    depends_on:
      - otel-collector

  sort-app:
    build: 
        context: .
        dockerfile: DockerfileSort
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector

