apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: opentelemetry
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: otlp-grpc
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: otlphttp
    - protocol: TCP
      port: 16686
      targetPort: 16686
      name: ui
---
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: opentelemetry
spec:
  selector:
    app: collector
  ports:
    - protocol: TCP
      port: 4320
      targetPort: 4320
      name: otlp-grpc
    - protocol: TCP
      port: 4321
      targetPort: 4321
      name: otlp-http
    - protocol: TCP
      port: 9464
      targetPort: 9464
      name: scrape
---
apiVersion: v1
kind: Service
metadata:
  name: api-endpoint
  namespace: opentelemetry
spec:
  selector:
    app: api-endpoint
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---

